import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Это стартовая страница</h1>
      <Link href="/FotoVideo">
        <a>FotoVideo</a>
      </Link>
      <br />
      <Link href="/Rout">
        <a>Rout</a>
      </Link>
      <br />
      <Link href="/Memoized">
        <a>Memoized</a>
      </Link>
      <br />
      <Link href="/Inputing">
        <a>Inputing</a>
      </Link>
      <br />

      <Link href="/mapBox">
        <a>mapBox</a>
      </Link>
    </div>
  );
}
